
const Discord = require('discord.js');
const Twana1 = new Discord.Client();
const Twana2 = new Discord.Client();
const Twana3 = new Discord.Client();
const Twana4 = new Discord.Client();
const Twana5 = new Discord.Client();
const Twana6 = new Discord.Client();
const Twana7 = new Discord.Client();
const Twana8 = new Discord.Client();
const Twana9 = new Discord.Client();
const Twana10 = new Discord.Client();
const Twana11 = new Discord.Client();
const Twana12 = new Discord.Client();
const Twana13 = new Discord.Client();
const Twana14 = new Discord.Client();
const Twana15 = new Discord.Client();
const Twana16 = new Discord.Client();
const Twana17 = new Discord.Client();
const Twana18 = new Discord.Client();
const Twana19 = new Discord.Client();
const Twana20 = new Discord.Client();
const Twana21 = new Discord.Client();
const Twana22 = new Discord.Client();
const Twana23 = new Discord.Client();
const Twana24 = new Discord.Client();
const Twana25 = new Discord.Client();
const Twana26 = new Discord.Client();
const Twana27 = new Discord.Client();
const Twana28 = new Discord.Client();
const Twana29 = new Discord.Client();
const Twana30 = new Discord.Client();
const Twana31 = new Discord.Client();
const Twana32 = new Discord.Client();
const Twana33 = new Discord.Client();
const Twana34 = new Discord.Client();
const Twana35 = new Discord.Client();
const Twana36 = new Discord.Client();
const Twana37 = new Discord.Client();
const Twana38 = new Discord.Client();
const Twana39 = new Discord.Client();
const Twana40 = new Discord.Client();
const Twana41 = new Discord.Client();
const Twana42 = new Discord.Client();
const Twana43 = new Discord.Client();
const Twana44 = new Discord.Client();
const Twana45 = new Discord.Client();
const Twana46 = new Discord.Client();
const Twana47 = new Discord.Client();
const Twana48 = new Discord.Client();
const Twana49 = new Discord.Client();
const Twana50 = new Discord.Client();
const Twana51 = new Discord.Client();
const Twana52 = new Discord.Client();
const Twana53 = new Discord.Client();
const Twana54 = new Discord.Client();
const Twana55 = new Discord.Client();
const Twana56 = new Discord.Client();
const Twana57 = new Discord.Client();
const Twana58 = new Discord.Client();
const Twana59 = new Discord.Client();
const Twana60 = new Discord.Client();
const Twana61 = new Discord.Client();
const Twana62 = new Discord.Client();
const Twana63 = new Discord.Client();
const Twana64 = new Discord.Client();
const Twana65 = new Discord.Client();
const Twana66 = new Discord.Client();
const Twana67 = new Discord.Client();
const Twana68 = new Discord.Client();
const Twana69 = new Discord.Client();
const Twana70 = new Discord.Client();
const Twana71 = new Discord.Client();
const Twana72 = new Discord.Client();
const Twana73 = new Discord.Client();
const Twana74 = new Discord.Client();
const Twana75 = new Discord.Client();
const Twana76 = new Discord.Client();
const Twana77 = new Discord.Client();
const Twana78 = new Discord.Client();
const Twana79 = new Discord.Client();
const Twana80 = new Discord.Client();
const Twana81 = new Discord.Client();
const Twana82 = new Discord.Client();
const Twana83 = new Discord.Client();
const Twana84 = new Discord.Client();
const Twana85 = new Discord.Client();
const Twana86 = new Discord.Client();
const Twana87 = new Discord.Client();
const Twana88 = new Discord.Client();
const Twana89 = new Discord.Client();
const Twana90 = new Discord.Client();
const Twana91 = new Discord.Client();
const Twana92 = new Discord.Client();
const Twana93 = new Discord.Client();
const Twana94 = new Discord.Client();
const Twana95 = new Discord.Client();
const Twana96 = new Discord.Client();
const Twana97 = new Discord.Client();
const Twana98 = new Discord.Client();
const Twana99 = new Discord.Client();
const Twana100= new Discord.Client();



Twana1.login("ODE1MzIxNjY1NTI4OTIyMTUz.YDqttQ.1VB-IfwuhCK22xuwRKs2zAcmjOY");
Twana2.login("ODE1MzIyNDAwNDcyMTcwNTY2.YDqu4A.-2lChdMT-pD7FOckvqYPTINWzDo");
Twana3.login("ODE1MzIyOTAxNTYwODE5Nzgz.YDqvcg.C1Ix6dk3CnFqBrVRPxcep4riokA");
Twana4.login("ODE1MzIzNTAyMjU3MTExMDQw.YDqwUQ.jGHlKV-3hquu2LtIhns6368W-3s");
Twana5.login("ODE1MzI0NDQ5OTg1MjY1NjY0.YDqxqA.1G6-guMfGwjXve9vsuejgreZ730");
Twana6.login("ODE1MzI1MDQ5MDYxMjQ0OTI4.YDqyaA.E5G2wA1EgnIy-UehXBmY99KSgnM");
Twana7.login("ODE1MzI1NTkzNDI2OTg0OTYx.YDqyfw.85br103nCVkeyDNGqc-xa5M_L3s");
Twana8.login("ODE1MzI2NjQzNDM3NDM2OTI5.YDqykQ.6u3-gPe8hB4nyV33PpZ5ZcD98Yw");
Twana9.login("ODE1MzI3NDMxODExNjYxODU0.YDqzCQ.mPavT3sOPagleRfIXoqMgpTeS6c");
Twana10.login("ODE1MzI4MTM2MjgyNTA1MjI3.YDqzsQ.b9LSR27CJqbiiEUjtCS0V7qnsoY");
Twana11.login("ODE1MzI4OTk0Njg4ODkyOTQ5.YDq0hA.w8hqThquYvPoB-IZyo7_JJeQgLU");
Twana12.login("ODE1MzI5NjE3ODA3Mjc4MDkw.YDrRVA.LThJo681uRfyvDw7EI6mih_aWlg");
Twana13.login("ODE1MzYwNjU0MDA1MzcwODgw.YDrSAA.9bqmknUMZAjo573iL8u4ZdcrJlI");
Twana14.login("ODE1MzYyNTEwMzEyMDQ2NjE0.YDrbmA.viS6EgDzYC8oPS2pvcDTbw03cOU");
Twana15.login("ODE1MzcxNjAyOTM2OTg3NzA4.YDrcMA.Isqtgo0jd7iqlMwkPy_stKUNwHk");
Twana16.login("ODE1MzcyNTcwNjU2MTEyNjYw.YDrdFg.DSHvrEuUk9-UE0cAQ5wZP2hiPVs");
Twana17.login("ODE1MzczMTg5NzQ3ODM0OTQw.YDrdqQ.G9udWswxKBJ6eWO3UUjtKGn5_xk");
Twana18.login("ODE1NjQ0NzYwOTE5NzY5MTA4.YDvbOQ.M0A1ESWibRGXcQtkUPZCUCQw7d0");
Twana19.login("ODE1NjQ1NzkwMDQ2NTE5MzI3.YDvcpw.h3zhkzBZe4KL1OyCHRMR4n0ydLM");
Twana20.login("ODE1NjQ3MjY3MTUxMjgyMTg3.YDvdwQ.oMA3G-6tt3YuTMN09_3s13j-wlU");
Twana21.login("ODE1NjQ4NzU1Nzc2NDg3NDk0.YDve6A.zhgNsKCPtULCoGKKE1qMJzDwMDI");
Twana22.login("ODE1NjQ5NjczNjkxMTM2MDMx.YDvfXw.eUMlW2hhOacmanDO4qxubVHB30g");
Twana23.login("ODE1NjUwMTc4ODQ4OTE1NDc3.YDvgBQ.N3ovYeLpR-8rDZ_XGY5fpm5187E");
Twana24.login("ODE1Mzc0NDk5NDE5Mzg5OTgz.YDvo2w.b2thoIL2oXbasuzSDpCrVAMaSP8");
Twana25.login("ODE1NjYwODY4NDE5MDU5NzUy.YDvplw.JmsxrfQRLcu3PfcnbdGB5n4YtJ8");
Twana26.login("ODE1NjYxNTc2Mjc5MDMxODc4.YDvqPg.GyEIzLFikaETEuJTU3MZ7_OWcGc");
Twana27.login("ODE1NjYyMjM5Mzk3ODM4ODU5.YDvq5Q.8hJRAzjl8C_2jmytrDCb_ZZfdIM");
Twana28.login("ODE1NjYxOTk1MTMwMDkzNjEw.YDvrPA.ChQ7WeNkaLf4XJq2iZhRYeYcrog");
Twana29.login("ODE1NjYyODA3MjI2Nzc3NjAw.YDvrXw.cAVqH3Ka3PMjwrzTyQoJ_Mah6rM");
Twana30.login("ODE1NjYyOTIxMzc5NDc5NTgz.YDvryQ.Aq0ziTYDgVI-6T8TnbPE5gFDF0g");
Twana31.login("ODE1NjYzMzY4ODQ4ODAxNzk0.YDvr9A.z0PcYrPqbXXtVtyCOf_WuVu0QNc");
Twana32.login("ODE1NjYzOTQ5NDg3NjY5MjQ4.YDvsdw.HZDbqjW01zBm8yhXXLDV0quZo0M");
Twana33.login("ODE1NjYzNDk4MDA0MDA0OTA3.YDvsiw.hUr2bhfWyiJVqzFCUQ_BZVCxBWg");
Twana34.login("ODE1NjY0NDQwOTI5NTUwMzY3.YDvtAw.WeFw8hTY7PonZ7gvBUNclJtwUw8");
Twana35.login("ODE1NjY0MzEyMjIyODc1NzE4.YDvtGA.VkvKmAV4CkkDd4vEALyP4Ka-KsE");
Twana36.login("ODE1NjY1MTY4NzYzNTg0NjAy.YDvtnw.vrqIgLbVC_4FVdrui_u4TohJT3w");
Twana37.login("ODE1NjY0OTIzMzUwNTMyMTk3.YDvt0Q.mrsvPM-C2RtG7rQscOYBtBfXvCE");
Twana38.login("ODE1NjY1NzEzMTU0MjI4MjQw.YDvuPA.v_RXKpSBs8MfxaP_WZtpgdnTc6M");
Twana39.login("ODE1NjY1Njc4NDA0NTUwNzA3.YDvuWw.c2kdC1y9_wBOjdScKE6iFHSlDJk");
Twana40.login("ODE1NjY2NjA1MDE4NTc4OTc0.YDvu6g.2rKsD_X_cagtWwhry6BK4GcMWNA");
Twana41.login("ODE1NjY3MTEzOTA5OTQ0Mzgy.YDvvZg.PL6VL8_huo7QIcWVjdy19BM7xK0");
Twana42.login("ODE1NjY3NjU4NzgzNTg4NDEz.YDvv8A._1LWvcJc8c8FGK0IkgAt_EyaAvE");
Twana43.login("ODE1NjY2MjUzOTY0MTE1OTc4.YDvxUw._5tAVnOCLwKgMSIC43Nb4lezuAY");
Twana44.login("ODE1NjY5NDc0NDkzNTk1NjQ4.YDvx7w.5ZpoydCv1k4xnmK-zkZrZqZm3Bc");
Twana45.login("ODE1NjcwMTAzMjAyMjAxNjIw.YDvywQ.CxieSSJ2rCeoMErJjbDAxETBQto");
Twana46.login("ODE1NjcwOTgyOTQxMzQzNzQ2.YDvzRQ.B5YlDAr9_9igFUYDxn1AcQoHl6E");
Twana47.login("ODE1NjcxNTMzNDQzMDg4NDA1.YDv0Gg.fCL_nMiyoP7h96n9Er-jEkwESGw");
Twana48.login("ODE1NjcyNDQyNzAwOTU1NjY5.YDv0uQ.gcSVJ89_QHRm9vFy-aLqWRV5O-g");
Twana49.login("ODE1NjczMTAwOTcxNjcxNjEz.YDv1SA.og0RT20xkPYKsJPquy6EbNyfgKk");
Twana50.login("ODE1NjczNjk5ODg1NTE0NzU0.YDv2bg.L0LrfhjEHgbbhaXaHj-edNT4Z4Y");
Twana51.login("ODE1Njc0OTM2MDc2Nzk1OTQ3.YDv7Ug.l-H5MVDkgeobjN3w5bPvPt66o-k");
Twana52.login("ODE1NjgwMTk0ODQ0ODE5NDk3.YDv7yw.fsnzBFb5tF44105YaVZNlkv9a5s");
Twana53.login("ODE1NjgwNjg3Njc4OTQ3MzU5.YDv-NA.GvZ_hHRbtat9nAwl7f7kZ_S7tdw");
Twana54.login("ODE1NjgzMjg1MzEyMjA4OTI4.YDv-vA.-gmCShXLv9n9AJ--lgoGyJfJAAg");
Twana55.login("ODE1NjgzODQ5MTU2OTUyMDg1.YDv_fw.xd-i94cgxL_MBv5biizgmMlMIHU");
Twana56.login("ODE1Njg0NjY2MTY5MjI5MzQy.YDwAEg.Nt2FYhK9Gd3mdd_SDzRh37BX9F8");
Twana57.login("ODE1Njg1MTY2MDM4Mzg0NjUw.YDwAQQ.NZ6Z0OFbiuOoOzgWQNzysrDXySA");
Twana58.login("ODE1Njg1OTIwNTM4NzU1MTAy.YDwBBA.ld47deb5WxB9qVdrnC16JN8GTwY");
Twana59.login("ODE1Njg2NTY1MjE2NTE4MTk2.YDwBgg.s8Vs-48SI9JWRNV_L3-MmgSOF3s");
Twana60.login("ODE1Njg1MjgxOTM5MTkzODk2.YDwBqA.iO0-3l4XpWUM6PTRJR-M4ZvsNH4");
Twana61.login("ODE1Njg2OTk0NjA4MjU5MTIz.YDwCTA.ZZSUQl2jhb5QgRiLy9QtixX9nGE");
Twana62.login("ODE1Njg3MDUwMDczMjEwOTcz.YDwCQw.1JH4EmA5sp3FQl0oEc5w6Bc4bdc");
Twana63.login("ODE1Njg3NjcxMDI0MTg5NTMx.YDwDCw.nAbfhUcSE7HTaLR2p6guzmqVcMY");
Twana64.login("ODE1Njg4MjU0NzczOTE5NzU1.YDwDNw.ad0IyN6AK7UWqvL9aUJQnyZ3PII");
Twana65.login("ODE1Njg4MzY3MzA3MDk2MDk0.YDwDvg.ynJjwzCXACaoZI6tokRTqmDhg4U");
Twana66.login("ODE1Njg5MDI2MzYzMzI2NDY1.YDwD1Q.goglobGgV2QqOq7nIMRdhvDvPxo");
Twana67.login("ODE1Njg5NjQ5Njg2MzE1MDE5.YDwEug.Fhvr0p3S864aFtndiJDriVuA1Vc");
Twana68.login("ODE1NjkwNTQ5NjExNzI0ODAx.YDwFNA.wzzl4nuY5AVZypE9il4HT0a2ooY");
Twana69.login("");
Twana70.login("");
Twana71.login("");
Twana72.login("");
Twana73.login("");
Twana74.login("");
Twana75.login("");
Twana76.login("");
Twana77.login("");
Twana78.login("");
Twana79.login("");
Twana80.login("");
Twana81.login("");
Twana82.login("");
Twana83.login("");
Twana84.login("");
Twana85.login("");
Twana86.login("");
Twana87.login("");
Twana88.login("");
Twana89.login("");
Twana90.login("");
Twana91.login("");
Twana92.login("");
Twana94.login("");
Twana95.login("");
Twana96.login("");
Twana97.login("");
Twana98.login("");
Twana99.login("");
Twana100.login("");









