
const Discord = require('discord.js');
const Twana1 = new Discord.Client();
const Twana2 = new Discord.Client();
const Twana3 = new Discord.Client();
const Twana4 = new Discord.Client();
const Twana5 = new Discord.Client();
const Twana6 = new Discord.Client();
const Twana7 = new Discord.Client();
const Twana8 = new Discord.Client();
const Twana9 = new Discord.Client();
const Twana10 = new Discord.Client();
const Twana11 = new Discord.Client();
const Twana12 = new Discord.Client();
const Twana13 = new Discord.Client();
const Twana14 = new Discord.Client();
const Twana15 = new Discord.Client();
const Twana16 = new Discord.Client();
const Twana17 = new Discord.Client();
const Twana18 = new Discord.Client();
const Twana19 = new Discord.Client();
const Twana20 = new Discord.Client();
const Twana21 = new Discord.Client();
const Twana22 = new Discord.Client();
const Twana23 = new Discord.Client();
const Twana24 = new Discord.Client();
const Twana25 = new Discord.Client();
const Twana26 = new Discord.Client();
const Twana27 = new Discord.Client();
const Twana28 = new Discord.Client();
const Twana29 = new Discord.Client();
const Twana30 = new Discord.Client();
const Twana31 = new Discord.Client();
const Twana32 = new Discord.Client();
const Twana33 = new Discord.Client();
const Twana34 = new Discord.Client();
const Twana35 = new Discord.Client();
const Twana36 = new Discord.Client();
const Twana37 = new Discord.Client();
const Twana38 = new Discord.Client();
const Twana39 = new Discord.Client();
const Twana40 = new Discord.Client();
const Twana41 = new Discord.Client();
const Twana42 = new Discord.Client();
const Twana43 = new Discord.Client();
const Twana44 = new Discord.Client();
const Twana45 = new Discord.Client();
const Twana46 = new Discord.Client();
const Twana47 = new Discord.Client();
const Twana48 = new Discord.Client();
const Twana49 = new Discord.Client();
const Twana50 = new Discord.Client();
const Twana51 = new Discord.Client();
const Twana52 = new Discord.Client();
const Twana53 = new Discord.Client();
const Twana54 = new Discord.Client();
const Twana55 = new Discord.Client();
const Twana56 = new Discord.Client();
const Twana57 = new Discord.Client();
const Twana58 = new Discord.Client();
const Twana59 = new Discord.Client();
const Twana60 = new Discord.Client();
const Twana61 = new Discord.Client();
const Twana62 = new Discord.Client();
const Twana63 = new Discord.Client();
const Twana64 = new Discord.Client();
const Twana65 = new Discord.Client();
const Twana66 = new Discord.Client();
const Twana67 = new Discord.Client();
const Twana68 = new Discord.Client();
const Twana69 = new Discord.Client();
const Twana70 = new Discord.Client();
const Twana71 = new Discord.Client();
const Twana72 = new Discord.Client();
const Twana73 = new Discord.Client();
const Twana74 = new Discord.Client();
const Twana75 = new Discord.Client();
const Twana76 = new Discord.Client();
const Twana77 = new Discord.Client();
const Twana78 = new Discord.Client();
const Twana79 = new Discord.Client();
const Twana80 = new Discord.Client();
const Twana81 = new Discord.Client();
const Twana82 = new Discord.Client();
const Twana83 = new Discord.Client();
const Twana84 = new Discord.Client();
const Twana85 = new Discord.Client();
const Twana86 = new Discord.Client();
const Twana87 = new Discord.Client();
const Twana88 = new Discord.Client();
const Twana89 = new Discord.Client();
const Twana90 = new Discord.Client();
const Twana91 = new Discord.Client();
const Twana92 = new Discord.Client();
const Twana93 = new Discord.Client();
const Twana94 = new Discord.Client();
const Twana95 = new Discord.Client();
const Twana96 = new Discord.Client();
const Twana97 = new Discord.Client();
const Twana98 = new Discord.Client();
const Twana99 = new Discord.Client();
const Twana100= new Discord.Client();



Twana1.login("");
Twana2.login("");
Twana3.login("");
Twana4.login("");
Twana5.login("");
Twana6.login("");
Twana7.login("");
Twana8.login("");
Twana9.login("");
Twana10.login("");
Twana11.login("");
Twana12.login("");
Twana13.login("");
Twana14.login("");
Twana15.login("");
Twana16.login("");
Twana17.login("");
Twana18.login("");
Twana19.login("");
Twana20.login("");
Twana21.login("");
Twana22.login("");
Twana23.login("");
Twana24.login("");
Twana25.login("");
Twana26.login("");
Twana27.login("");
Twana28.login("");
Twana29.login("");
Twana30.login("");
Twana31.login("");
Twana32.login("");
Twana33.login("");
Twana34.login("");
Twana35.login("");
Twana36.login("");
Twana37.login("");
Twana38.login("");
Twana39.login("");
Twana40.login("");
Twana41.login("");
Twana42.login("");
Twana43.login("");
Twana44.login("");
Twana45.login("");
Twana46.login("");
Twana47.login("");
Twana48.login("");
Twana49.login("");
Twana50.login("");
Twana51.login("");
Twana52.login("");
Twana53.login("");
Twana54.login("");
Twana55.login("");
Twana56.login("");
Twana57.login("");
Twana58.login("");
Twana59.login("");
Twana60.login("");
Twana61.login("");
Twana62.login("");
Twana63.login("");
Twana64.login("");
Twana65.login("");
Twana66.login("");
Twana67.login("");
Twana68.login("");
Twana69.login("");
Twana70.login("");
Twana71.login("");
Twana72.login("");
Twana73.login("");
Twana74.login("");
Twana75.login("");
Twana76.login("");
Twana77.login("");
Twana78.login("");
Twana79.login("");
Twana80.login("");
Twana81.login("");
Twana82.login("");
Twana83.login("");
Twana84.login("");
Twana85.login("");
Twana86.login("");
Twana87.login("");
Twana88.login("");
Twana89.login("");
Twana90.login("");
Twana91.login("");
Twana92.login("");
Twana94.login("");
Twana95.login("");
Twana96.login("");
Twana97.login("");
Twana98.login("");
Twana99.login("");
Twana100.login("");









